services:
  kafka:
    image: bitnami/kafka:3.7
    ports:
      - 9092:9092
    container_name: kafka
    volumes:
      - ./persistence-data-kafka:/bitnami/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - data-ingestion-practice 

networks:
  data-ingestion-practice:
    name: data-ingestion-practice
    external: true